"""periods reorganize migration

Revision ID: 0219c3ed136a
Revises: 6c1d9ea13398
Create Date: 2023-07-28 11:36:06.203214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0219c3ed136a'
down_revision = '6c1d9ea13398'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
