"""First migration

Revision ID: 225aff3a45c9
Revises: 
Create Date: 2023-04-12 13:37:51.623024

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '225aff3a45c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=40), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('classrooms',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('days',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=11), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=3), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('periods',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.Time(), nullable=True),
                    sa.Column('end_time', sa.Time(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('schools',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('subjects',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=40), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('schedules',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('school_id', sa.Integer(), nullable=True),
                    sa.Column('day_id', sa.Integer(), nullable=True),
                    sa.Column('period_id', sa.Integer(), nullable=True),
                    sa.Column('subject_id', sa.Integer(), nullable=True),
                    sa.Column('classroom_id', sa.Integer(), nullable=True),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
                    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
                    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
                    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('schedules')
    op.drop_table('schools')
    op.drop_table('periods')
    op.drop_table('groups')
    op.drop_table('days')
    op.drop_table('classrooms')
    op.drop_table('cities')
    # ### end Alembic commands ###
