"""admin table migration

Revision ID: 346f28cc8a22
Revises: b64e7147e655
Create Date: 2023-07-26 12:12:51.512210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346f28cc8a22'
down_revision = 'b64e7147e655'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
