"""rebirth migration

Revision ID: 4df6a2c76f98
Revises: 6bd1202041e2
Create Date: 2023-07-24 10:41:15.726221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4df6a2c76f98'
down_revision = '6bd1202041e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('classrooms', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('days', 'name',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('groups', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('periods', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('periods', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('schedules', 'day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedules', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedules', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedules', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedules', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedules', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schools', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schools', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('teachers', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teachers', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('teachers', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('schools', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('schools', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedules', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedules', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedules', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedules', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedules', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedules', 'day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('periods', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('periods', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('groups', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('days', 'name',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('classrooms', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
