"""add permissions migration

Revision ID: 6c1d9ea13398
Revises: e266314dbe7c
Create Date: 2023-07-28 08:07:20.168670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1d9ea13398'
down_revision = 'e266314dbe7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
