"""Little fix tables migration

Revision ID: c07a2c0e4de8
Revises: 225aff3a45c9
Create Date: 2023-06-13 08:18:43.428599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c07a2c0e4de8'
down_revision = '225aff3a45c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('teachers')
    op.drop_table('classrooms')
    op.drop_table('groups')
    op.drop_table('schools')
    op.drop_table('days')
    op.drop_table('cities')
    op.drop_table('periods')
    op.drop_table('subjects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('classrooms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('classrooms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='classrooms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('teachers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teachers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teachers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('subjects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('periods',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('periods_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='periods_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('schools',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('schools_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='schools_city_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='schools_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('classroom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name='schedules_classroom_id_fkey'),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], name='schedules_day_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='schedules_group_id_fkey'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], name='schedules_period_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='schedules_school_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='schedules_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='schedules_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='schedules_pkey')
    )
    op.create_table('cities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cities_pkey')
    )
    op.create_table('days',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='days_pkey')
    )
    # ### end Alembic commands ###
